# Generated by Django 5.1.4 on 2025-07-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
