# Generated by Django 5.1.4 on 2025-07-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_customer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [
                    ("cancel_order", "Can cancel order"),
                    ("view_history", "Can View history"),
                ],
            },
        ),
    ]
