# Generated by Django 5.1.4 on 2025-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_collection_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
